# Generated by Django 2.2.7 on 2019-11-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servico', '0002_auto_20191110_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='preco',
            new_name='preco_servico',
        ),
    ]
