# Generated by Django 2.2.7 on 2019-11-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_auto_20191110_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created',), 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
