# Generated by Django 2.2.7 on 2019-11-10 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_auto_20191110_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Postagem')),
                ('status_pedido', models.PositiveSmallIntegerField(choices=[(0, 'Pedido Realizado'), (1, 'Concluído'), (2, 'Cancelado')], default=0, verbose_name='Situação')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Pedido.Status', verbose_name='Status'),
        ),
    ]
