# Generated by Django 2.2.7 on 2019-11-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_auto_20191110_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roupa',
            old_name='preco',
            new_name='preco_roupa',
        ),
    ]
