# Generated by Django 2.2.7 on 2019-11-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Pedido', '0006_auto_20191110_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='solicitante',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='Home.Cliente', verbose_name='Nome Cliente'),
            preserve_default=False,
        ),
    ]
