# Generated by Django 2.2.7 on 2019-11-10 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0007_pedido_solicitante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='descricao',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='status',
            name='data_postagem',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_solicitacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Postagem'),
        ),
    ]
