# Generated by Django 2.2.7 on 2019-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0008_auto_20191110_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='comentario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
    ]
