# Generated by Django 2.2.7 on 2019-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0009_auto_20191110_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
