# Generated by Django 2.2.7 on 2019-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0010_auto_20191110_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentar_status_pedido',
            field=models.TextField(blank=True, null=True, verbose_name='Comentar Status'),
        ),
    ]
