# Generated by Django 2.2.7 on 2019-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0012_pedido_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[(0, 'Boleto Bancário'), (1, 'Cartão de Debíto'), (2, 'Cartão de Credito'), (3, 'Transferencia Bancária')], default=0, max_length=50, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_pedido',
            field=models.CharField(choices=[(0, 'Pedido Realizado'), (1, 'Concluído'), (2, 'Cancelado')], default=0, max_length=50, verbose_name='Situação'),
        ),
    ]
