# Generated by Django 2.2.7 on 2019-11-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0013_auto_20191110_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('Boleto Bancário', 'Boleto Bancário'), ('Cartão de Debíto', 'Cartão de Debíto'), ('Cartão de Credito', 'Cartão de Credito'), ('Transferencia Bancária', 'Transferencia Bancária')], default='Boleto Bancário', max_length=50, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_pedido',
            field=models.CharField(choices=[('Pedido Realizado', 'Pedido Realizado'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pedido Realizado', max_length=50, verbose_name='Situação'),
        ),
    ]
