# Generated by Django 2.2.7 on 2019-11-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0016_auto_20191110_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_pedido',
            new_name='situacao_pedido',
        ),
    ]
