# Generated by Django 2.2.7 on 2019-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0017_auto_20191110_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='comentario',
            field=models.TextField(default=1, verbose_name='Comentar Status'),
            preserve_default=False,
        ),
    ]
