# Generated by Django 2.2.7 on 2019-11-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0018_auto_20191110_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
