# Generated by Django 2.2.7 on 2019-11-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0020_suporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='numero_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Pedido.Pedido', verbose_name='Número do Pedido'),
        ),
    ]
