# Generated by Django 2.2.7 on 2019-11-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0021_auto_20191115_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='mensagem',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
