# Generated by Django 2.2.7 on 2019-11-16 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0022_suporte_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='cpf',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(11111111111)], verbose_name=' CPF '),
        ),
    ]
