# Generated by Django 2.2.7 on 2019-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0023_auto_20191116_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='numero_pedido',
        ),
        migrations.RemoveField(
            model_name='suporte',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='suporte',
            name='nome_cliente',
            field=models.CharField(max_length=50, verbose_name='Nome do Cliente'),
        ),
    ]
