# Generated by Django 2.2.7 on 2019-11-16 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0025_auto_20191116_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 5, 55, 39, 164883, tzinfo=utc), null=True),
        ),
    ]
