# Generated by Django 2.2.7 on 2019-11-16 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0026_suporte_data_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 14, 24, 9, 413785, tzinfo=utc), null=True),
        ),
    ]
