# Generated by Django 2.2.7 on 2019-11-16 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0027_auto_20191116_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 14, 28, 58, 527635, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='respondido',
            field=models.BooleanField(default=False, verbose_name='Respondido'),
        ),
    ]
