# Generated by Django 2.2.7 on 2019-11-16 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0028_auto_20191116_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 15, 10, 15, 849871, tzinfo=utc), null=True),
        ),
    ]
