# Generated by Django 2.2.7 on 2019-11-16 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0030_auto_20191116_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='respondido',
        ),
        migrations.AddField(
            model_name='suporte',
            name='resposta',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 16, 20, 55, 45, 512501, tzinfo=utc), null=True),
        ),
    ]
