# Generated by Django 2.2.7 on 2019-11-17 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0031_auto_20191116_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('Boleto Bancário', 'Boleto Bancário'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Transferência Bancária', 'Transferência Bancária')], default='Boleto Bancário', max_length=50, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 17, 0, 38, 49, 516024, tzinfo=utc), null=True),
        ),
    ]
