# Generated by Django 2.2.7 on 2019-11-17 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0032_auto_20191116_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='situacao_pedido',
            field=models.CharField(choices=[('Pedido Ativo', 'Pedido Ativo'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Pedido Cancelado', 'Pedido Cancelado')], default='Pedido Ativo', max_length=50, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 17, 0, 49, 51, 573107, tzinfo=utc), null=True),
        ),
    ]
