# Generated by Django 2.2.7 on 2019-11-17 01:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0033_auto_20191116_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_pedido', models.CharField(choices=[('Pedido Ativo', 'Pedido Ativo'), ('Pedido Finalizado', 'Pedido Finalizado'), ('Pedido Cancelado', 'Pedido Cancelado')], default='Pedido Ativo', max_length=50, verbose_name='Situação')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='situacao_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedido.StatusPedido', verbose_name='Status Pedido'),
        ),
        migrations.AlterField(
            model_name='status',
            name='situacao_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedido.StatusPedido', verbose_name='Status do Pedido'),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 17, 1, 1, 31, 289094, tzinfo=utc), null=True),
        ),
    ]
