# Generated by Django 2.2.7 on 2019-11-17 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0034_auto_20191116_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 17, 1, 2, 52, 620966, tzinfo=utc), null=True),
        ),
    ]
