# Generated by Django 2.2.7 on 2019-11-17 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0035_auto_20191116_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 17, 1, 3, 2, 156535, tzinfo=utc), null=True),
        ),
    ]
