# Generated by Django 2.2.7 on 2019-11-17 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0036_auto_20191116_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='data_mensagem',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 17, 4, 9, 2, 947691, tzinfo=utc), null=True),
        ),
    ]
