# Generated by Django 2.2.7 on 2019-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0038_auto_20191117_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
