# Generated by Django 2.2.7 on 2019-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0039_auto_20191117_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Valor Total'),
        ),
    ]
