# Generated by Django 2.2.7 on 2019-11-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0041_auto_20191120_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suporte',
            name='data_mensagem',
        ),
    ]
