# Generated by Django 2.2.7 on 2019-11-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0043_suporte_data_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='situacao_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Pedido.StatusPedido', verbose_name='Status Pedido'),
        ),
    ]
